SEED_MODELS = [
    {
        "id": "replicate:flux-schnell",
        "provider": "replicate",
        "provider_model_id": "black-forest-labs/flux-schnell",
        "name": "Flux Schnell",
        "family": "flux",
        "description": "Fast image generation model by Black Forest Labs",
        "media_types": ["image"],
        "capabilities": {"max_width": 1024, "max_height": 1024, "supports_seed": True},
        "default_params": {"width": 1024, "height": 1024},
        "cost_per_unit": 0.002,
        "cost_unit": "per_image",
        "tags": ["fast", "general"],
    },
    {
        "id": "replicate:flux-pro",
        "provider": "replicate",
        "provider_model_id": "black-forest-labs/flux-pro",
        "name": "Flux Pro",
        "family": "flux",
        "description": "Premium high-quality image generation by Black Forest Labs",
        "media_types": ["image"],
        "capabilities": {"max_width": 1440, "max_height": 1440, "supports_seed": True,
                         "supports_negative_prompt": True},
        "default_params": {"width": 1024, "height": 1024},
        "cost_per_unit": 0.050,
        "cost_unit": "per_image",
        "tags": ["premium", "high-quality"],
    },
    {
        "id": "replicate:sdxl",
        "provider": "replicate",
        "provider_model_id": "stability-ai/sdxl",
        "name": "SDXL",
        "family": "sdxl",
        "description": "Stable Diffusion XL — open-source image generation",
        "media_types": ["image"],
        "capabilities": {"max_width": 1024, "max_height": 1024, "supports_seed": True,
                         "supports_negative_prompt": True},
        "default_params": {"width": 1024, "height": 1024},
        "cost_per_unit": 0.010,
        "cost_unit": "per_image",
        "tags": ["general", "open-source"],
    },
    {
        "id": "openai:dall-e-3",
        "provider": "openai",
        "provider_model_id": "dall-e-3",
        "name": "DALL-E 3",
        "family": "dall-e",
        "description": "OpenAI's latest image generation model",
        "media_types": ["image"],
        "status": "coming_soon",
        "capabilities": {"max_width": 1792, "max_height": 1024},
        "default_params": {"width": 1024, "height": 1024},
        "tags": ["premium"],
    },
]
